baseURL = "https://j3ssie.github.io/Osmedeus/"
# baseURL = "/"
languageCode = "en-us"
title = "Osmedeus Documentation"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
staticDir = ["static"]
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "j3ssie"
  # Description of the site, will be used in meta information
  description = "Fully automated offensive security framework for reconnaissance and vulnerability scanning"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "jaeles"

[Languages]

[[Languages.en.menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/j3ssie/Osmedeus"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-book'></i> API Details"
url = "https://documenter.getpostman.com/view/7482578/S1a626XR?version=latest"
weight = 11
